export const ERROR_CODES = {
  // General
  INTERNAL_ERROR: 'INTERNAL_ERROR',
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  NOT_FOUND: 'NOT_FOUND',
  UNAUTHORIZED: 'UNAUTHORIZED',
  FORBIDDEN: 'FORBIDDEN',
  CONFLICT: 'CONFLICT',

  // Business Logic
  BUSINESS_ERROR: 'BUSINESS_ERROR',
  INVALID_OPERATION: 'INVALID_OPERATION',
  INSUFFICIENT_STOCK: 'INSUFFICIENT_STOCK',
  INVALID_PRICE: 'INVALID_PRICE',

  // Entity Specific
  ENTITY_NOT_FOUND: 'ENTITY_NOT_FOUND',
  PRODUCT_NOT_FOUND: 'PRODUCT_NOT_FOUND',
  ALREADY_EXISTS: 'ALREADY_EXISTS',
  PRODUCT_NAME_EXISTS: 'PRODUCT_NAME_EXISTS',

  // System
  DATABASE_ERROR: 'DATABASE_ERROR',
  CACHE_ERROR: 'CACHE_ERROR',
  EXTERNAL_SERVICE_ERROR: 'EXTERNAL_SERVICE_ERROR',
} as const;

export type ErrorCode = (typeof ERROR_CODES)[keyof typeof ERROR_CODES];
